In [54]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [55]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Cherskiy,RU,2021-10-09 04:52:48,68.7500,161.3000,6.76,95,67,1.66
1,1,New Norfolk,AU,2021-10-09 04:52:48,-42.7826,147.0587,62.10,52,94,4.00
2,2,Nikolskoye,RU,2021-10-09 04:52:49,59.7035,30.7861,51.87,74,100,6.96
3,3,Conde,BR,2021-10-09 04:52:49,-7.2597,-34.9075,74.66,94,20,4.61
4,4,Copiapo,CL,2021-10-09 04:52:49,-27.3667,-70.3333,47.89,68,0,2.30

In [56]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [57]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [58]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
    
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp,0) for temp in max_temp], 
                                 dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [59]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [60]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [61]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [62]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [63]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
9,9,Izumo,JP,2021-10-09 04:52:51,35.3667,132.7667,80.49,69,40,18.41
13,13,Hasaki,JP,2021-10-09 04:52:52,35.7333,140.8333,75.60,82,92,14.94
14,14,Cockburn Town,TC,2021-10-09 04:52:52,21.4612,-71.1419,82.18,78,4,12.95
28,28,Callaway,US,2021-10-09 04:52:56,30.1530,-85.5699,75.13,80,1,1.99
29,29,Olinda,BR,2021-10-09 04:52:58,-8.0089,-34.8553,78.53,78,40,8.05
31,31,Kapaa,US,2021-10-09 04:52:58,22.0752,-159.3190,79.12,70,40,5.01
34,34,Atuona,PF,2021-10-09 04:50:54,-9.8000,-139.0333,78.03,76,15,15.79
35,35,Tiarei,PF,2021-10-09 04:52:59,-17.5333,-149.3333,78.82,69,36,2.68
39,39,Sao Filipe,CV,2021-10-09 04:53:01,14.8961,-24.4956,79.27,81,50,7.96
61,61,Araguacu,BR,2021-10-09 04:53:08,-12.9306,-49.8264,83.53,40,33,0.81

In [64]:
preferred_cities_df.count()

City_ID       156
City          156
Country       156
Date          156
Lat           156
Lng           156
Max Temp      156
Humidity      156
Cloudiness    156
Wind Speed    156
dtype: int64

In [65]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

             City Country  Max Temp      Lat       Lng Hotel Name
9           Izumo      JP     80.49  35.3667  132.7667
13         Hasaki      JP     75.60  35.7333  140.8333
14  Cockburn Town      TC     82.18  21.4612  -71.1419
28       Callaway      US     75.13  30.1530  -85.5699
29         Olinda      BR     78.53  -8.0089  -34.8553
31          Kapaa      US     79.12  22.0752 -159.3190
34         Atuona      PF     78.03  -9.8000 -139.0333
35         Tiarei      PF     78.82 -17.5333 -149.3333
39     Sao Filipe      CV     79.27  14.8961  -24.4956
61       Araguacu      BR     83.53 -12.9306  -49.8264

In [66]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "hotel",
    "key": g_key
}

In [67]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [68]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
        print('Hotel for ' + hotel_df.loc[index, 'City'] + ' is: ' + hotel_df.loc[index, "Hotel Name"])
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel for Izumo is: Izumo
Hotel for Hasaki is: Kamisu
Hotel for Cockburn Town is: Cockburn Town
Hotel for Callaway is: Panama City
Hotel for Olinda is: Olinda
Hotel for Kapaa is: Kapaʻa
Hotel for Atuona is: Atuona
Hotel for Tiarei is: Maha'ena
Hotel for Sao Filipe is: Sao Filipe
Hotel for Araguacu is: Araguaçu
Hotel for Hithadhoo is: Addu City
Hotel for Victoria is: Hong Kong
Hotel for Wattegama is: Wattegama
Hotel for Tecoanapa is: Barra de Tecoanapa
Hotel for Mbekenyera is: Mbekenyera
Hotel for Lorengau is: Lorengau
Hotel for Faanui is: Vaitape
Hotel for Bengkulu is: Bengkulu
Hotel for Tera is: Tera
Hotel for Auki is: Auki
Hotel for Mindelo is: Mindelo
Hotel for Green Valley is: Green Valley
Hotel for Vaini is: Nukuhetulu
Hotel for Itarema is: Itarema
Hotel for Hilo is: Hilo
Hotel for Atar is: Atar
Hotel for Salinopolis is: Salinópolis
Hotel for Manggar is: Manggar
Hotel for Butaritari is: Ukiangang
Hotel for Coahuayana is: Coahuayana de Hidalgo
Hotel for Bubaque is: Bubaque
Hotel for Kilindoni is: Kilindoni
Hotel for San Blas is: San Blas
Hotel for Illela is: Illiea
Hotel for Namatanai is: Namatanai
Hotel for Lakes Entrance is: Lakes Entrance
Hotel for Jagraon is: Jagraon
Hotel for Gigmoto is: Gigmoto
Hotel for Contai is: Contai
Hotel for Road Town is: Road Town
Hotel for Katsuura is: Katsuura
Hotel for Catio is: Catió
Hotel for Seoul is: Seoul
Hotel not found... skipping.
Hotel for Puerto Ayacucho is: Puerto Ayacucho
Hotel for Padang is: Padang
Hotel for Nizwa is: Nizwa
Hotel for Avarua is: Avarua District
Hotel for Shimoda is: Shimoda
Hotel for Bodden Town is: Bodden Town
Hotel for Dalbandin is: Dalbandin
Hotel for Takoradi is: Takoradi
Hotel for Ternate is: Ternate
Hotel for Tura is: Tura
Hotel for Tateyama is: Minamiboso
Hotel for Gweta is: Gweta
Hotel for Cabo San Lucas is: Cabo San Lucas
Hotel for Champerico is: Champerico
Hotel for Salalah is: Salalah
Hotel for Riohacha is: Riohacha
Hotel for San Antonio is: San Antonio
Hotel for Ugoofaaru is: Ungoofaaru
Hotel for Bandarbeyla is: Bandarbeyla
Hotel for Bathsheba is: Wilson Hill
Hotel for Bam is: Bam
Hotel for Airai is: Atsabe
Hotel for Acapulco is: Acapulco
Hotel for Manokwari is: Manokwari
Hotel for Hambantota is: Hambantota
Hotel for Nishihara is: Naha
Hotel for Shizilu is: Linyi
Hotel for Kahului is: Kahului
Hotel for Mogadishu is: Mogadishu
Hotel for San Patricio is: Sinton
Hotel for The Valley is: The Valley
Hotel for Taoudenni is: Taoudenni
Hotel for Atambua is: Atambua
Hotel for Ahuimanu is: Honolulu
Hotel for Garissa is: Garissa
Hotel for Naze is: Amami
Hotel for Hervey Bay is: Hervey Bay
Hotel for Vanimo is: Vanimo
Hotel for Dubbo is: Dubbo
Hotel for Tautira is: Tautira
Hotel for Basco is: Basco
Hotel for Diu is: Diu
Hotel for Moerai is: Moerai
Hotel for Sulangan is: Bantayan
Hotel for Itamaraca is: Ilha de Itamaracá
Hotel for Terenos is: Terenos
Hotel for Amahai is: Amahai
Hotel for Mucurapo is: Port of Spain
Hotel for Katobu is: Kampani
Hotel for Lonar is: Lonar
Hotel for Gamba is: Foundou
Hotel for Hai Duong is: Hải Dương
Hotel for Kavieng is: Kavieng
Hotel for Banda Aceh is: Banda Aceh
Hotel for Kloulklubed is: Klouklubed
Hotel for Cayenne is: Cayenne
Hotel for Fare is: Fare
Hotel for Soyo is: Soyo
Hotel for Puro is: Aroroy
Hotel for Omboue is: Omboue
Hotel for Celestun is: Celestún
Hotel for Riyadh is: Riyadh
Hotel for Aborlan is: Aborlan
Hotel for Dingle is: Pototan
Hotel for Nelson Bay is: Nelson Bay - Corlette
Hotel for Tamalameque is: Tamalameque
Hotel for Muroto is: Muroto
Hotel for Matara is: Matara
Hotel for Samarai is: Magesina
Hotel for Port Blair is: Port Blair
Hotel for Sola is: Sola
Hotel for Bourail is: Bourail
Hotel for Saint-Georges is: Saint George's
Hotel for Clarence Town is: Clarence Town
Hotel for Masuguru is: Masuguru
Hotel for Marsh Harbour is: Marsh Harbour
Hotel for Bac Lieu is: Bạc Liêu
Hotel for Rio Muerto is: San Ignacio Río Muerto
Hotel for Isangel is: Isangel
Hotel for Gabu is: Gabu
Hotel for Balingasay is: Bolinao
Hotel for Teknaf is: Teknaf
Hotel for Wagar is: Wagga
Hotel for Port Hedland is: Port Hedland
Hotel for Kameyama is: Tsu
Hotel for Pasni is: Pasni
Hotel for Tecoman is: Tecomán
Hotel for Simimbaan is: Roxas
Hotel for Caborca is: Santa Ana
Hotel for Kathmandu is: Kathmandu
Hotel for Sao Felix Do Xingu is: São Félix do Xingu
Hotel for Jaruco is: Jaruco
Hotel for Paracuru is: Paracuru
Hotel for Aden is: Aden
Hotel for Ballina is: Ballina
Hotel for Port Macquarie is: Port Macquarie
Hotel for Tanga is: Tanga
Hotel for Nagato is: Nagato
Hotel for Lazaro Cardenas is: Lázaro Cárdenas
Hotel for Doka is: Doka
Hotel for Gizo is: Gizo
Hotel for Puerto Escondido is: Puerto Escondido
Hotel for Sinnamary is: Sinnamary
Hotel for Goalpara is: Goalpara
Hotel for Touros is: Touros
Hotel for Ambon is: Teluk Ambon
Hotel for Hobyo is: Hobyo
Hotel for Mangrol is: Mangrol
Hotel for Aquiraz is: Eusébio
Hotel for Biak is: CV. Karya Alam Perkasa
Hotel for Tebingtinggi is: Tebing Tinggi
Hotel for Sambava is: Sambava

In [69]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [70]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [71]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [72]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))